---
teams:
- name: WhiteTeam
  color: White
  users:
  - username: whiteteamuser
    password: democracy-beans-1337
- name: RedTeam
  color: Red
  users:
  - username: redteamuser
    password: redteamlovesyou
